baseURL: "http://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "hugo-PaperMod"

# Theme settings
params:
    ShowReadingTime: true

baseURL: https://paul-gd.github.io/

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true